const LANGUAGE_DEFAULT_INPUT = "DEFAULT"
const LANGUAGE_DEFAULT_ISO = process.env.LANGUAGE_DEFAULT_ISO || "SAN"
const DEFAULT_ENTITY_THUMBNAIL = 'https://picsum.photos/300/250'

module.exports = {
  LANGUAGE_DEFAULT_INPUT,
  LANGUAGE_DEFAULT_ISO,
  DEFAULT_ENTITY_THUMBNAIL,
}