# Generated by Django 3.0.7 on 2020-06-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql_api.Language')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql_api.Entity')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql_api.EntityType')),
            ],
        ),
        migrations.CreateModel(
            name='EntityMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql_api.Entity')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql_api.EntityType')),
            ],
        ),
    ]
