# Generated by Django 3.0.7 on 2020-06-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0002_entitymeta_entitytext'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
