# Generated by Django 3.0.7 on 2020-06-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0003_language_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitytext',
            old_name='name',
            new_name='text',
        ),
    ]
