# Generated by Django 3.0.7 on 2020-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0005_auto_20200613_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='default_text',
            field=models.CharField(default='default_text', max_length=50),
            preserve_default=False,
        ),
    ]
