# Generated by Django 3.0.7 on 2020-06-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0006_entity_default_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='entitymeta',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entitytext',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
