# Generated by Django 3.0.7 on 2020-06-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0008_auto_20200619_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='default_thumbnail',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tags',
            field=models.TextField(blank=True, default='https://via.placeholder.com/250?text=$text'),
        ),
    ]
