# Generated by Django 3.0.7 on 2020-06-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0010_auto_20200621_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='default_thumbnail',
            field=models.URLField(default='https://via.placeholder.com/250?text=$text'),
        ),
    ]
