# Generated by Django 3.0.7 on 2020-06-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0011_auto_20200621_1522'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contentline',
            constraint=models.UniqueConstraint(fields=('parent', 'language'), name='Entity Unique Language'),
        ),
    ]
