# Generated by Django 3.0.7 on 2020-06-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0012_auto_20200625_1408'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentline',
            name='Entity Unique Language',
        ),
        migrations.AddConstraint(
            model_name='contentline',
            constraint=models.UniqueConstraint(fields=('parent', 'language'), name='Entity_Unique_Language'),
        ),
    ]
