# Generated by Django 3.0.7 on 2020-07-02 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0015_auto_20200625_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gql_api.Entity')),
            ],
        ),
    ]
