# Generated by Django 3.0.7 on 2020-07-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0016_bookmarks'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmarks',
            constraint=models.UniqueConstraint(fields=('entity',), name='Bookmark_Unique_Entity'),
        ),
    ]
