# Generated by Django 3.0.7 on 2020-07-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gql_api', '0017_auto_20200704_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='local', max_length=50)),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bookmarks',
            name='Bookmark_Unique_Entity',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='user',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='bookmarks',
            constraint=models.UniqueConstraint(fields=('user', 'entity'), name='Bookmark_Unique_Entity'),
        ),
        migrations.AddConstraint(
            model_name='settings',
            constraint=models.UniqueConstraint(fields=('user',), name='Settings_Unique_User'),
        ),
    ]
